name: 'Build LaTeX CV'
on:
  push: tags-ignore

jobs:
  build:
    name: Build CV
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          working_directory: cv/
