name: 'Build LaTeX CV'
on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
    paths-ignore:
      - 'README.md'
      - 'cvpic.png'
      - '.gitignore'
      - 'Makefile'
      - 'old/*'

jobs:
  build:
    name: Build CV
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex

      - uses: actions/upload-artifact@v3
        with:
          name: cv.pdf
          path: cv.pdf
