name: 'Build and Publish LaTeX CV'
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_publish:
    name: Build CV
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          working_directory: cv/

      - uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: cv/cv.pdf

  publish:
    name: Publish CV
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - uses: actions/download-artifact@v2
        with:
          name: cv.pdf

      - name: Upload Release CV
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cv/cv.pdf
          asset_name: cv.pdf
          asset_content_type: application/pdf
